spring:
  profiles:
    include: oauth

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://main-database.c3al47kbxqk7.ap-northeast-2.rds.amazonaws.com:3306/main_database?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: sijun
    password: xogns0538!!
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

server:
  servlet:
    encoding:
      force-response: true
cloud:
  aws:
    s3:
      bucket: my-github-actions-s3-burket
    credentials:
      access-key: AKIATYK3GYSCFHHJCTAY
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
jwt:
  temporary-token-expiration-ms: 1800000
  secret: woduddl13@@